// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnhdgoY4TWUwk-DATu5rVJMZkHYtx5tFc',
    appId: '1:782614324251:android:4a108fc02d344ff74304be',
    messagingSenderId: '782614324251',
    projectId: 'withcenter-meetup-2',
    databaseURL: 'https://withcenter-meetup-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'withcenter-meetup-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCubhiJIat4_WpjJuVVOWr3KCN3xM4-Jfc',
    appId: '1:782614324251:ios:e7ab4138a295f6ba4304be',
    messagingSenderId: '782614324251',
    projectId: 'withcenter-meetup-2',
    databaseURL: 'https://withcenter-meetup-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'withcenter-meetup-2.appspot.com',
    iosBundleId: 'com.withcenter.wemeet',
  );
}
