List<Map> koreanRootCode = [
  {"rnum": 1, "code": "1", "name": "서울"},
  {"rnum": 2, "code": "2", "name": "인천"},
  {"rnum": 3, "code": "3", "name": "대전"},
  {"rnum": 4, "code": "4", "name": "대구"},
  {"rnum": 5, "code": "5", "name": "광주"},
  {"rnum": 6, "code": "6", "name": "부산"},
  {"rnum": 7, "code": "7", "name": "울산"},
  {"rnum": 8, "code": "8", "name": "세종특별자치시"},
  {"rnum": 9, "code": "31", "name": "경기도"},
  {"rnum": 10, "code": "32", "name": "강원특별자치도"},
  {"rnum": 11, "code": "33", "name": "충청북도"},
  {"rnum": 12, "code": "34", "name": "충청남도"},
  {"rnum": 13, "code": "35", "name": "경상북도"},
  {"rnum": 14, "code": "36", "name": "경상남도"},
  {"rnum": 15, "code": "37", "name": "전북특별자치도"},
  {"rnum": 16, "code": "38", "name": "전라남도"},
  {"rnum": 17, "code": "39", "name": "제주도"}
];
List<Map> englishRootCodes = [
  {"rnum": 1, "code": "1", "name": "Seoul"},
  {"rnum": 2, "code": "2", "name": "Incheon"},
  {"rnum": 3, "code": "3", "name": "Daejeon"},
  {"rnum": 4, "code": "4", "name": "Daegu"},
  {"rnum": 5, "code": "5", "name": "Gwangju"},
  {"rnum": 6, "code": "6", "name": "Busan"},
  {"rnum": 7, "code": "7", "name": "Ulsan"},
  {"rnum": 8, "code": "8", "name": "Sejong"},
  {"rnum": 9, "code": "31", "name": "Gyeonggi-do"},
  {"rnum": 10, "code": "32", "name": "Gangwon-do"},
  {"rnum": 11, "code": "33", "name": "Chungcheongbuk-do"},
  {"rnum": 12, "code": "34", "name": "Chungcheongnam-do"},
  {"rnum": 13, "code": "35", "name": "Gyeongsangbuk-do"},
  {"rnum": 14, "code": "36", "name": "Gyeongsangnam-do"},
  {"rnum": 15, "code": "37", "name": "Jeollabuk-do"},
  {"rnum": 16, "code": "38", "name": "Jeollanam-do"},
  {"rnum": 17, "code": "39", "name": "Jeju-do"}
];
