// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGQGmmz9RmNRU4X7gsnejOVwBKveUHh3s',
    appId: '1:391614224917:web:946e3ecf62e6a5e42c0c1c',
    messagingSenderId: '391614224917',
    projectId: 'withcenter-test-project',
    authDomain: 'withcenter-test-project.firebaseapp.com',
    databaseURL: 'https://withcenter-test-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'withcenter-test-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb8TWG0oDhBfuHRwWGt7M3xEMQRJr3d-Y',
    appId: '1:391614224917:android:c6150fb0525306692c0c1c',
    messagingSenderId: '391614224917',
    projectId: 'withcenter-test-project',
    databaseURL: 'https://withcenter-test-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'withcenter-test-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABMW6ugWVFUgzdC7ucsa4GTa4f5HidqrQ',
    appId: '1:391614224917:ios:610c17c8d39b47dc2c0c1c',
    messagingSenderId: '391614224917',
    projectId: 'withcenter-test-project',
    databaseURL: 'https://withcenter-test-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'withcenter-test-project.appspot.com',
    androidClientId: '391614224917-0lp7b5c9kaiuta5o68o5jfpfiaj07p79.apps.googleusercontent.com',
    iosClientId: '391614224917-6l4m30gc14g178oro6oteqte5k0fcb4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );
}
